title = "My New Hugo Site"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pageref = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageref = "/about"
    weight = 20
    
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pageref = "/"
    weight = 1