title = "Soup for thought"

baseURL = "https://soupforthoughtdev.netlify.app/"
relativeURLs = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blogs"
    pageref = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageref = "/about"
    weight = 20
    
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pageref = "/"
    weight = 1